#!/usr/bin/env bash
[[ "$DOTFILES_APPLY" != true || $(uname -s) == Darwin ]] || die "The macos profile can only be installed on macOS"

link_file "$DOTFILES_ROOT/config/git/gitconfig" "$HOME/.gitconfig"
link_file "$DOTFILES_ROOT/config/git/gitignore" "$HOME/.gitignore"
link_file "$DOTFILES_ROOT/config/kitty" "$HOME/.config/kitty"
link_file "$DOTFILES_ROOT/config/ghostty" "$HOME/.config/ghostty"
link_file "$DOTFILES_ROOT/config/alacritty" "$HOME/.config/alacritty"
link_file "$DOTFILES_ROOT/config/nvim" "$HOME/.config/nvim"
link_file "$DOTFILES_ROOT/config/tmux/tmux.conf" "$HOME/.tmux.conf"
link_file "$DOTFILES_ROOT/config/tmux/themes" "$HOME/.tmux/themes"
link_file "$DOTFILES_ROOT/config/tmux/scripts" "$HOME/.tmux/scripts"
link_file "$DOTFILES_ROOT/config/zsh/zshenv" "$HOME/.zshenv"
link_file "$DOTFILES_ROOT/config/zsh/zshrc" "$HOME/.zshrc"
link_file "$DOTFILES_ROOT/config/zsh/zprofile" "$HOME/.zprofile"
link_file "$DOTFILES_ROOT/config/zsh/p10k.zsh" "$HOME/.zsh/p10k.zsh"
link_file "$DOTFILES_ROOT/config/zsh/p10k-overrides.zsh" "$HOME/.zsh/p10k-overrides.zsh"
link_file "$DOTFILES_ROOT/quotes/quotes.txt" "$HOME/.quotes.txt"
link_file "$DOTFILES_ROOT/bin/project-switcher" "$HOME/bin/p"
link_file "$DOTFILES_ROOT/bin/ray" "$HOME/bin/ray"
