[tools]
node = "latest"
python = "latest"
go = "latest"
ruby = "latest"
neovim = "latest"
tmux = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
lazygit = "latest"
yazi = "latest"
gum = "latest"
yt-dlp = "latest"
ansible = "latest"
