filetype: git-config

detect:
    filename: "git(config|modules)$|\\.git/config$"

rules:
    - constant: "\\<(true|false)\\>"
    - type.keyword: "^[[:space:]]*[^=]*="
    - constant: "^[[:space:]]*\\[.*\\]$"
    - constant: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"
    - comment:
        start: "#"
        end: "$"
        rules: []
