# godoc
# example: go doc -all | micro 

filetype: godoc

detect:
    filename: "\\.godoc$"
    header: package.*import

rules:
    - preproc: "^[^ ].*"

    - comment:
        start: "//"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
