filetype: ini

detect:
    filename: "\\.(ini|desktop|lfl|override|tscn|tres)$|(mimeapps\\.list|pinforc|setup\\.cfg|project\\.godot)$|weechat/.+\\.conf$"

rules:
    - constant.bool.true: "\\btrue\\b"
    - constant.bool.false: "\\bfalse\\b"
    - identifier: "^[[:space:]]*[^=]*="
    - special: "^[[:space:]]*\\[.*\\]$"
    - statement: "[=;]"
    - constant.string: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"

    - comment:
        start: "#"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
    - comment:
        start: ";"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
