filetype: patch

detect:
    filename: "\\.(patch|diff)$"
    header: "^diff"

rules:
    - brightgreen: "^\\+.*"
    - green: "^\\+\\+\\+.*"
    - brightblue: "^ .*"
    - brightred: "^-.*"
    - red: "^---.*"
    - brightyellow: "^@@.*"
    - magenta: "^diff.*"
