filetype: tex

detect: 
    filename: "\\.tex$|\\.bib$|\\.cls$"

rules:
    # colorize the identifiers of {<identifier>} and [<identifier>]
    - identifier:
        start: "\\{"
        end: "\\}"
        rules: []
    - identifier:
        start: "\\["
        end: "\\]"
        rules: []
    # numbers
    - constant.number: "\\b[0-9]+(\\.[0-9]+)?([[:space:]](pt|mm|cm|in|ex|em|bp|pc|dd|cc|nd|nc|sp))?\\b"
    # let brackets have the default color again
    - default: "[{}\\[\\]]"
    - special: "[&\\\\]"
    # macros
    - statement: "\\\\@?[a-zA-Z_]+"
    - statement: "\\\\%"
    # comments
    - comment:
        start: "[^\\\\]%|^%"
        end: "$"
        rules: []
    - comment:
        start: "\\\\begin\\{comment\\}"
        end: "\\\\end\\{comment\\}"
        rules: []
