filetype: xml

detect:
    filename: "\\.(xml|sgml?|rng|svg|plist)$"
    header: "<\\?xml.*\\?>"

rules:
    - preproc:
        start: "<!DOCTYPE"
        end: "[/]?>"
        rules: []

    - comment:
        start: "<!--"
        end: "-->"
        rules: []

    - symbol.tag:
        start: "<\\??"
        end: "\\??>"
        rules:
            - identifier:
                start: " "
                end: "="
                rules: []
            - constant.string:
                start: "\""
                end: "\""
                skip: "\\\\."
                rules:
                    - constant.specialChar: "\\\\."
            - constant.string:
                start: "'"
                end: "'"
                skip: "\\\\."
                rules:
                    - constant.specialChar: "\\\\."
