# Add local ~/.bin to PATH
# Add global composer bin to PATH
export PATH="$HOME/bin":"$HOME/.composer/vendor/bin":$PATH

########
# Herd #
########

# Push toolbox App at the end of the PATH
export PATH="$PATH:/Users/vuppi/Library/Application Support/JetBrains/Toolbox/scripts"

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
